name: CI - ft_transcendence

on:
  push:
    branches: ["master", "dev", "feature/*"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  check-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check repository
        run: |
          if [ -f .env ]; then echo " Error: .env file detected in repo!"; exit 1; fi
          if [ -d node_modules ]; then echo " Error: node_modules detected in repo!"; exit 1; fi
          echo " Repository is clean."

  build-test:
    needs: check-repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Secrets for CI
        run: |
          mkdir -p infra/secret
          openssl rand -base64 32 > infra/secret/jwt_secret.txt
          openssl rand -base64 32 > infra/secret/vault_token.txt
          echo "Dummy secrets created."

      - name: Start Services
        run: |
          docker compose build auth-service api-gateway redis vault
          docker compose up -d auth-service api-gateway redis vault

      - name: Wait for Health
        run: |
          echo "Waiting for services to stabilize..."
          sleep 15
          docker compose ps

      #    We use SKIP_PROTECTED=true because User Service is not running yet.
      - name: Run JWT Flow Test
        env:
          GATEWAY_URL: http://localhost:3000
          SKIP_PROTECTED: true
        run: |
          chmod +x ./scripts/test_jwt_flow.sh
          ./scripts/test_jwt_flow.sh

      - name: Dump Logs on Failure
        if: failure()
        run: docker compose logs
